import PlayArrowIcon from "@mui/icons-material/PlayArrow";
import ShareIcon from "@mui/icons-material/Share";
import RecentActorsIcon from "@mui/icons-material/RecentActors";

export const quizeData = [
  {
    id: 24,
    title: "Which Mindset Do You Have?",
    image:
      "https://dk7h1f5gq849l.cloudfront.net/quiz_images/17631034812958eaab-4d30-4736-904a-2f47d9564b6e.png",
    questions: 10,
    plays: "450",
    btn: [
      { label: "Play", icon: <PlayArrowIcon /> },
      { label: "Flashcards", icon: <RecentActorsIcon /> },
      { label: "Play With Friends", icon: <ShareIcon /> },
    ],
    type: "personality",
    allQuestion: [
      {
        qid: 10,
        question: "How do you react to a new challenge?",
        options: [
          "I avoid it",
          "I try but get nervous",
          "I do my best",
          "I feel excited to learn",
        ],
        answer: 4,
      },
      {
        qid: 9,
        question: "What motivates you the most?",
        options: [
          "Rewards",
          "Learning new things",
          "Avoiding failure",
          "Proving others wrong",
        ],
        answer: 2,
      },
      {
        qid: 1,
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Venus"],
        answer: 2,
      },
      {
        qid: 2,
        question: "What is the largest mammal in the world?",
        options: ["Elephant", "Blue Whale", "Giraffe", "Polar Bear"],
        answer: 2,
      },
      {
        qid: 3,
        question: "What is the boiling point of water?",
        options: ["50°C", "100°C", "80°C", "120°C"],
        answer: 2,
      },
      {
        qid: 4,
        question: "Which gas do plants absorb during photosynthesis?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
        answer: 2,
      },
      {
        qid: 5,
        question: "Who wrote 'Harry Potter'?",
        options: [
          "J.K. Rowling",
          "Charles Dickens",
          "William Shakespeare",
          "George Orwell",
        ],
        answer: 1,
      },
      {
        qid: 6,
        question: "Which is the largest ocean on Earth?",
        options: [
          "Indian Ocean",
          "Pacific Ocean",
          "Atlantic Ocean",
          "Arctic Ocean",
        ],
        answer: 2,
      },
      {
        qid: 7,
        question: "What is the capital of France?",
        options: ["Paris", "Rome", "Berlin", "Madrid"],
        answer: 1,
      },
      {
        qid: 8,
        question: "How many bones are in the adult human body?",
        options: ["206", "150", "180", "220"],
        answer: 1,
      },
    ],
  },
  {
    id: 125,
    title: "Which Black Panther Character Are You?",
    image:
      "https://dk7h1f5gq849l.cloudfront.net/quiz_images/17631034812958eaab-4d30-4736-904a-2f47d9564b6e.png",
    questions: 10,
    plays: "180",
    btn: [
      { label: "Play", icon: <PlayArrowIcon /> },
      { label: "Flashcards", icon: <RecentActorsIcon /> },
      { label: "Play With Friends", icon: <ShareIcon /> },
    ],
    type: "personality",
    allQuestion: [
      {
        qid: 10,
        question: "How do you react to a new challenge?",
        options: [
          "I avoid it",
          "I try but get nervous",
          "I do my best",
          "I feel excited to learn",
        ],
        answer: 4,
      },
      {
        qid: 9,
        question: "What motivates you the most?",
        options: [
          "Rewards",
          "Learning new things",
          "Avoiding failure",
          "Proving others wrong",
        ],
        answer: 2,
      },
      {
        qid: 1,
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Venus"],
        answer: 2,
      },
      {
        qid: 2,
        question: "What is the largest mammal in the world?",
        options: ["Elephant", "Blue Whale", "Giraffe", "Polar Bear"],
        answer: 2,
      },
      {
        qid: 3,
        question: "What is the boiling point of water?",
        options: ["50°C", "100°C", "80°C", "120°C"],
        answer: 2,
      },
      {
        qid: 4,
        question: "Which gas do plants absorb during photosynthesis?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
        answer: 2,
      },
      {
        qid: 5,
        question: "Who wrote 'Harry Potter'?",
        options: [
          "J.K. Rowling",
          "Charles Dickens",
          "William Shakespeare",
          "George Orwell",
        ],
        answer: 1,
      },
      {
        qid: 6,
        question: "Which is the largest ocean on Earth?",
        options: [
          "Indian Ocean",
          "Pacific Ocean",
          "Atlantic Ocean",
          "Arctic Ocean",
        ],
        answer: 2,
      },
      {
        qid: 7,
        question: "What is the capital of France?",
        options: ["Paris", "Rome", "Berlin", "Madrid"],
        answer: 1,
      },
      {
        qid: 8,
        question: "How many bones are in the adult human body?",
        options: ["206", "150", "180", "220"],
        answer: 1,
      },
    ],
  },
  {
    id: 126,
    title: "Which Oppenheimer Character Are You?",
    image:
      "https://dk7h1f5gq849l.cloudfront.net/quiz_images/17631034812958eaab-4d30-4736-904a-2f47d9564b6e.png",
    questions: 10,
    plays: "95",
    btn: [
      { label: "Play", icon: <PlayArrowIcon /> },
      { label: "Flashcards", icon: <RecentActorsIcon /> },
      { label: "Play With Friends", icon: <ShareIcon /> },
    ],
    type: "personality",
    allQuestion: [
      {
        qid: 10,
        question: "How do you react to a new challenge?",
        options: [
          "I avoid it",
          "I try but get nervous",
          "I do my best",
          "I feel excited to learn",
        ],
        answer: 4,
      },
      {
        qid: 9,
        question: "What motivates you the most?",
        options: [
          "Rewards",
          "Learning new things",
          "Avoiding failure",
          "Proving others wrong",
        ],
        answer: 2,
      },
      {
        qid: 1,
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Venus"],
        answer: 2,
      },
      {
        qid: 2,
        question: "What is the largest mammal in the world?",
        options: ["Elephant", "Blue Whale", "Giraffe", "Polar Bear"],
        answer: 2,
      },
      {
        qid: 3,
        question: "What is the boiling point of water?",
        options: ["50°C", "100°C", "80°C", "120°C"],
        answer: 2,
      },
      {
        qid: 4,
        question: "Which gas do plants absorb during photosynthesis?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
        answer: 2,
      },
      {
        qid: 5,
        question: "Who wrote 'Harry Potter'?",
        options: [
          "J.K. Rowling",
          "Charles Dickens",
          "William Shakespeare",
          "George Orwell",
        ],
        answer: 1,
      },
      {
        qid: 6,
        question: "Which is the largest ocean on Earth?",
        options: [
          "Indian Ocean",
          "Pacific Ocean",
          "Atlantic Ocean",
          "Arctic Ocean",
        ],
        answer: 2,
      },
      {
        qid: 7,
        question: "What is the capital of France?",
        options: ["Paris", "Rome", "Berlin", "Madrid"],
        answer: 1,
      },
      {
        qid: 8,
        question: "How many bones are in the adult human body?",
        options: ["206", "150", "180", "220"],
        answer: 1,
      },
    ],
  },
  {
    id: 127,
    title: "Which Brooklyn 99 Character Are You?",
    image:
      "https://dk7h1f5gq849l.cloudfront.net/quiz_images/17631034812958eaab-4d30-4736-904a-2f47d9564b6e.png",
    questions: 10,
    plays: "230",
    btn: [
      { label: "Play", icon: <PlayArrowIcon /> },
      { label: "Flashcards", icon: <RecentActorsIcon /> },
      { label: "Play With Friends", icon: <ShareIcon /> },
    ],
    type: "personality",
    allQuestion: [
      {
        qid: 10,
        question: "How do you react to a new challenge?",
        options: [
          "I avoid it",
          "I try but get nervous",
          "I do my best",
          "I feel excited to learn",
        ],
        answer: 4,
      },
      {
        qid: 9,
        question: "What motivates you the most?",
        options: [
          "Rewards",
          "Learning new things",
          "Avoiding failure",
          "Proving others wrong",
        ],
        answer: 2,
      },
      {
        qid: 1,
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Venus"],
        answer: 2,
      },
      {
        qid: 2,
        question: "What is the largest mammal in the world?",
        options: ["Elephant", "Blue Whale", "Giraffe", "Polar Bear"],
        answer: 2,
      },
      {
        qid: 3,
        question: "What is the boiling point of water?",
        options: ["50°C", "100°C", "80°C", "120°C"],
        answer: 2,
      },
      {
        qid: 4,
        question: "Which gas do plants absorb during photosynthesis?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
        answer: 2,
      },
      {
        qid: 5,
        question: "Who wrote 'Harry Potter'?",
        options: [
          "J.K. Rowling",
          "Charles Dickens",
          "William Shakespeare",
          "George Orwell",
        ],
        answer: 1,
      },
      {
        qid: 6,
        question: "Which is the largest ocean on Earth?",
        options: [
          "Indian Ocean",
          "Pacific Ocean",
          "Atlantic Ocean",
          "Arctic Ocean",
        ],
        answer: 2,
      },
      {
        qid: 7,
        question: "What is the capital of France?",
        options: ["Paris", "Rome", "Berlin", "Madrid"],
        answer: 1,
      },
      {
        qid: 8,
        question: "How many bones are in the adult human body?",
        options: ["206", "150", "180", "220"],
        answer: 1,
      },
    ],
  },
  {
    id: 128,
    title: "Which Suits Character Are You?",
    image:
      "https://dk7h1f5gq849l.cloudfront.net/quiz_images/17631034812958eaab-4d30-4736-904a-2f47d9564b6e.png",
    questions: 10,
    plays: "200",
    btn: [
      { label: "Play", icon: <PlayArrowIcon /> },
      { label: "Flashcards", icon: <RecentActorsIcon /> },
      { label: "Play With Friends", icon: <ShareIcon /> },
    ],
    type: "personality",
    allQuestion: [
      {
        qid: 10,
        question: "How do you react to a new challenge?",
        options: [
          "I avoid it",
          "I try but get nervous",
          "I do my best",
          "I feel excited to learn",
        ],
        answer: 4,
      },
      {
        qid: 9,
        question: "What motivates you the most?",
        options: [
          "Rewards",
          "Learning new things",
          "Avoiding failure",
          "Proving others wrong",
        ],
        answer: 2,
      },
      {
        qid: 1,
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Venus"],
        answer: 2,
      },
      {
        qid: 2,
        question: "What is the largest mammal in the world?",
        options: ["Elephant", "Blue Whale", "Giraffe", "Polar Bear"],
        answer: 2,
      },
      {
        qid: 3,
        question: "What is the boiling point of water?",
        options: ["50°C", "100°C", "80°C", "120°C"],
        answer: 2,
      },
      {
        qid: 4,
        question: "Which gas do plants absorb during photosynthesis?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
        answer: 2,
      },
      {
        qid: 5,
        question: "Who wrote 'Harry Potter'?",
        options: [
          "J.K. Rowling",
          "Charles Dickens",
          "William Shakespeare",
          "George Orwell",
        ],
        answer: 1,
      },
      {
        qid: 6,
        question: "Which is the largest ocean on Earth?",
        options: [
          "Indian Ocean",
          "Pacific Ocean",
          "Atlantic Ocean",
          "Arctic Ocean",
        ],
        answer: 2,
      },
      {
        qid: 7,
        question: "What is the capital of France?",
        options: ["Paris", "Rome", "Berlin", "Madrid"],
        answer: 1,
      },
      {
        qid: 8,
        question: "How many bones are in the adult human body?",
        options: ["206", "150", "180", "220"],
        answer: 1,
      },
    ],
  },
  {
    id: 124,
    title: "Dr. Doe's Chemistry Quiz",
    image:
      "https://dk7h1f5gq849l.cloudfront.net/quiz_images/17631034812958eaab-4d30-4736-904a-2f47d9564b6e.png",
    questions: 10,
    plays: "1.3k",
    btn: [
      { label: "Play", icon: <PlayArrowIcon /> },
      { label: "Flashcards", icon: <RecentActorsIcon /> },
      { label: "Play With Friends", icon: <ShareIcon /> },
    ],
    type: "trending",
    allQuestion: [
      {
        qid: 10,
        question: "How do you react to a new challenge?",
        options: [
          "I avoid it",
          "I try but get nervous",
          "I do my best",
          "I feel excited to learn",
        ],
        answer: 4,
      },
      {
        qid: 9,
        question: "What motivates you the most?",
        options: [
          "Rewards",
          "Learning new things",
          "Avoiding failure",
          "Proving others wrong",
        ],
        answer: 2,
      },
      {
        qid: 1,
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Venus"],
        answer: 2,
      },
      {
        qid: 2,
        question: "What is the largest mammal in the world?",
        options: ["Elephant", "Blue Whale", "Giraffe", "Polar Bear"],
        answer: 2,
      },
      {
        qid: 3,
        question: "What is the boiling point of water?",
        options: ["50°C", "100°C", "80°C", "120°C"],
        answer: 2,
      },
      {
        qid: 4,
        question: "Which gas do plants absorb during photosynthesis?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
        answer: 2,
      },
      {
        qid: 5,
        question: "Who wrote 'Harry Potter'?",
        options: [
          "J.K. Rowling",
          "Charles Dickens",
          "William Shakespeare",
          "George Orwell",
        ],
        answer: 1,
      },
      {
        qid: 6,
        question: "Which is the largest ocean on Earth?",
        options: [
          "Indian Ocean",
          "Pacific Ocean",
          "Atlantic Ocean",
          "Arctic Ocean",
        ],
        answer: 2,
      },
      {
        qid: 7,
        question: "What is the capital of France?",
        options: ["Paris", "Rome", "Berlin", "Madrid"],
        answer: 1,
      },
      {
        qid: 8,
        question: "How many bones are in the adult human body?",
        options: ["206", "150", "180", "220"],
        answer: 1,
      },
    ],
  },
  {
    id: 125,
    title: "Guess The Word By Emoji",
    image:
      "https://dk7h1f5gq849l.cloudfront.net/quiz_images/17631034812958eaab-4d30-4736-904a-2f47d9564b6e.png",
    questions: 10,
    plays: "135",
    btn: [
      { label: "Play", icon: <PlayArrowIcon /> },
      { label: "Flashcards", icon: <RecentActorsIcon /> },
      { label: "Play With Friends", icon: <ShareIcon /> },
    ],
    type: "trending",
    allQuestion: [
      {
        qid: 10,
        question: "How do you react to a new challenge?",
        options: [
          "I avoid it",
          "I try but get nervous",
          "I do my best",
          "I feel excited to learn",
        ],
        answer: 4,
      },
      {
        qid: 9,
        question: "What motivates you the most?",
        options: [
          "Rewards",
          "Learning new things",
          "Avoiding failure",
          "Proving others wrong",
        ],
        answer: 2,
      },
      {
        qid: 1,
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Venus"],
        answer: 2,
      },
      {
        qid: 2,
        question: "What is the largest mammal in the world?",
        options: ["Elephant", "Blue Whale", "Giraffe", "Polar Bear"],
        answer: 2,
      },
      {
        qid: 3,
        question: "What is the boiling point of water?",
        options: ["50°C", "100°C", "80°C", "120°C"],
        answer: 2,
      },
      {
        qid: 4,
        question: "Which gas do plants absorb during photosynthesis?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
        answer: 2,
      },
      {
        qid: 5,
        question: "Who wrote 'Harry Potter'?",
        options: [
          "J.K. Rowling",
          "Charles Dickens",
          "William Shakespeare",
          "George Orwell",
        ],
        answer: 1,
      },
      {
        qid: 6,
        question: "Which is the largest ocean on Earth?",
        options: [
          "Indian Ocean",
          "Pacific Ocean",
          "Atlantic Ocean",
          "Arctic Ocean",
        ],
        answer: 2,
      },
      {
        qid: 7,
        question: "What is the capital of France?",
        options: ["Paris", "Rome", "Berlin", "Madrid"],
        answer: 1,
      },
      {
        qid: 8,
        question: "How many bones are in the adult human body?",
        options: ["206", "150", "180", "220"],
        answer: 1,
      },
    ],
  },
  {
    id: 126,
    title: "Dr. Doe’s Chemistry Quiz 2",
    image:
      "https://dk7h1f5gq849l.cloudfront.net/quiz_images/17631034812958eaab-4d30-4736-904a-2f47d9564b6e.png",
    questions: 10,
    plays: "36",
    btn: [
      { label: "Play", icon: <PlayArrowIcon /> },
      { label: "Flashcards", icon: <RecentActorsIcon /> },
      { label: "Play With Friends", icon: <ShareIcon /> },
    ],
    type: "trending",
    allQuestion: [
      {
        qid: 10,
        question: "How do you react to a new challenge?",
        options: [
          "I avoid it",
          "I try but get nervous",
          "I do my best",
          "I feel excited to learn",
        ],
        answer: 4,
      },
      {
        qid: 9,
        question: "What motivates you the most?",
        options: [
          "Rewards",
          "Learning new things",
          "Avoiding failure",
          "Proving others wrong",
        ],
        answer: 2,
      },
      {
        qid: 1,
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Venus"],
        answer: 2,
      },
      {
        qid: 2,
        question: "What is the largest mammal in the world?",
        options: ["Elephant", "Blue Whale", "Giraffe", "Polar Bear"],
        answer: 2,
      },
      {
        qid: 3,
        question: "What is the boiling point of water?",
        options: ["50°C", "100°C", "80°C", "120°C"],
        answer: 2,
      },
      {
        qid: 4,
        question: "Which gas do plants absorb during photosynthesis?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
        answer: 2,
      },
      {
        qid: 5,
        question: "Who wrote 'Harry Potter'?",
        options: [
          "J.K. Rowling",
          "Charles Dickens",
          "William Shakespeare",
          "George Orwell",
        ],
        answer: 1,
      },
      {
        qid: 6,
        question: "Which is the largest ocean on Earth?",
        options: [
          "Indian Ocean",
          "Pacific Ocean",
          "Atlantic Ocean",
          "Arctic Ocean",
        ],
        answer: 2,
      },
      {
        qid: 7,
        question: "What is the capital of France?",
        options: ["Paris", "Rome", "Berlin", "Madrid"],
        answer: 1,
      },
      {
        qid: 8,
        question: "How many bones are in the adult human body?",
        options: ["206", "150", "180", "220"],
        answer: 1,
      },
    ],
  },
  {
    id: 127,
    title: "Black Friday Quiz",
    image:
      "https://dk7h1f5gq849l.cloudfront.net/quiz_images/17631034812958eaab-4d30-4736-904a-2f47d9564b6e.png",
    questions: 10,
    plays: "7",
    btn: [
      { label: "Play", icon: <PlayArrowIcon /> },
      { label: "Flashcards", icon: <RecentActorsIcon /> },
      { label: "Play With Friends", icon: <ShareIcon /> },
    ],
    type: "trending",
    allQuestion: [
      {
        qid: 10,
        question: "How do you react to a new challenge?",
        options: [
          "I avoid it",
          "I try but get nervous",
          "I do my best",
          "I feel excited to learn",
        ],
        answer: 4,
      },
      {
        qid: 9,
        question: "What motivates you the most?",
        options: [
          "Rewards",
          "Learning new things",
          "Avoiding failure",
          "Proving others wrong",
        ],
        answer: 2,
      },
      {
        qid: 1,
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Venus"],
        answer: 2,
      },
      {
        qid: 2,
        question: "What is the largest mammal in the world?",
        options: ["Elephant", "Blue Whale", "Giraffe", "Polar Bear"],
        answer: 2,
      },
      {
        qid: 3,
        question: "What is the boiling point of water?",
        options: ["50°C", "100°C", "80°C", "120°C"],
        answer: 2,
      },
      {
        qid: 4,
        question: "Which gas do plants absorb during photosynthesis?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
        answer: 2,
      },
      {
        qid: 5,
        question: "Who wrote 'Harry Potter'?",
        options: [
          "J.K. Rowling",
          "Charles Dickens",
          "William Shakespeare",
          "George Orwell",
        ],
        answer: 1,
      },
      {
        qid: 6,
        question: "Which is the largest ocean on Earth?",
        options: [
          "Indian Ocean",
          "Pacific Ocean",
          "Atlantic Ocean",
          "Arctic Ocean",
        ],
        answer: 2,
      },
      {
        qid: 7,
        question: "What is the capital of France?",
        options: ["Paris", "Rome", "Berlin", "Madrid"],
        answer: 1,
      },
      {
        qid: 8,
        question: "How many bones are in the adult human body?",
        options: ["206", "150", "180", "220"],
        answer: 1,
      },
    ],
  },
  {
    id: 128,
    title: "Guess The Singer!",
    image:
      "https://dk7h1f5gq849l.cloudfront.net/quiz_images/17631034812958eaab-4d30-4736-904a-2f47d9564b6e.png",
    questions: 10,
    plays: "40",
    btn: [
      { label: "Play", icon: <PlayArrowIcon /> },
      { label: "Flashcards", icon: <RecentActorsIcon /> },
      { label: "Play With Friends", icon: <ShareIcon /> },
    ],
    type: "trending",
    allQuestion: [
      {
        qid: 10,
        question: "How do you react to a new challenge?",
        options: [
          "I avoid it",
          "I try but get nervous",
          "I do my best",
          "I feel excited to learn",
        ],
        answer: 4,
      },
      {
        qid: 9,
        question: "What motivates you the most?",
        options: [
          "Rewards",
          "Learning new things",
          "Avoiding failure",
          "Proving others wrong",
        ],
        answer: 2,
      },
      {
        qid: 1,
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Venus"],
        answer: 2,
      },
      {
        qid: 2,
        question: "What is the largest mammal in the world?",
        options: ["Elephant", "Blue Whale", "Giraffe", "Polar Bear"],
        answer: 2,
      },
      {
        qid: 3,
        question: "What is the boiling point of water?",
        options: ["50°C", "100°C", "80°C", "120°C"],
        answer: 2,
      },
      {
        qid: 4,
        question: "Which gas do plants absorb during photosynthesis?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
        answer: 2,
      },
      {
        qid: 5,
        question: "Who wrote 'Harry Potter'?",
        options: [
          "J.K. Rowling",
          "Charles Dickens",
          "William Shakespeare",
          "George Orwell",
        ],
        answer: 1,
      },
      {
        qid: 6,
        question: "Which is the largest ocean on Earth?",
        options: [
          "Indian Ocean",
          "Pacific Ocean",
          "Atlantic Ocean",
          "Arctic Ocean",
        ],
        answer: 2,
      },
      {
        qid: 7,
        question: "What is the capital of France?",
        options: ["Paris", "Rome", "Berlin", "Madrid"],
        answer: 1,
      },
      {
        qid: 8,
        question: "How many bones are in the adult human body?",
        options: ["206", "150", "180", "220"],
        answer: 1,
      },
    ],
  },
];
